.github/dependabot.yml
.github/workflows/ci_cd.yml

Add custom workflow for release to github, because there is not pdf artifact. Tha pyansys/actions will look for pdf.
Add assignees to pyansys-ci-bot for dependabot , and give write access to the ci bot

CI : Add custom release to github

---

src/ansys/motorcad/core/geometry.py

I noticed that the geometry 'unite' function had an incorrect docstring, copied from 'subtract'.

Correct docstrings for geometry.unite

---

src/ansys/motorcad/core/geometry.py
tests/test_geometry.py

previous arc length calculation had problems, replaced with a simpler calculation that relies of the total_angle() class method/property of arcs

Corrected calculation of arc length

---

examples/adaptive_library/BPMTriangularRotorNotches.py
examples/adaptive_library/BezierCurveRotorPockets.py
examples/adaptive_library/TrapezoidalDuct.py
examples/adaptive_library/UShapeSYNCRELCurvedFluxBarriers.py

Does what it says on the tin.
Before:
After:

Fix sphinx gallery thumbnails

---

src/ansys/motorcad/core/geometry.py

We were checking 'if distance' and similar, to check if a named parameter had been passed, as this is False if distance is None. However, it is also false if the distance is set, and is equal to 0. This explicitly checks 'is None'/'is not None'.

Correct get_coordinate_from_distance if zero value is passed to a named parameter

---

doc/source/methods/index.rst

We are getting a warning on every PR because this 'Oxford comma' was missing in the documentation.

Add Oxford comma to satisfy vale.

---

src/ansys/motorcad/core/methods/rpc_methods_ui.py

Updating the Docstrings for save_screen_to_file to avoid confusion. Previously it was not clear that this command needs a different screen name format to display_screen and save_motorcad_screen_to_file.

Updating the Docstrings for save_screen_to_file

---

LICENSE
examples/adaptive_library/BPMTriangularRotorNotches.py
examples/adaptive_library/BezierCurveRotorPockets.py
examples/adaptive_library/OblongStatorDuct.py
examples/adaptive_library/RoundParallelSlotBttm.py
examples/adaptive_library/TrapezoidalDuct.py
src/ansys/motorcad/core/methods/adaptive_geometry.py
tests/test_geometry.py

In many of the adaptive template examples, we define a function that creates an adaptive template parameter with a default value, if the parameter does not already exist (otherwise the parameter is left unchanged). 
This PR adds a PyMotorCAD method to do this, to reduce duplicated code in the examples, and make this easier for users.

Add set_adaptive_parameter_default method

---

src/ansys/motorcad/core/methods/rpc_methods_graphs.py
tests/test_graphs.py

This implements a method to give the user the harmonic orders, amplitudes and phase angles from a magnetic graph. These are currently easily visible in Motor-CAD, but hard to access via PyMotorCAD.
Closes #430 
Example code to test with:
```
import ansys.motorcad.core as pym
import matplotlib.pyplot as plt
mc = pym.MotorCAD(open_new_instance=False)
orders, amp, ang = mc.get_magnetic_graph_harmonics("TerminalLineToLine12")
fig, axs = plt.subplots(2)
axs[0].bar(orders, amp)
axs[1].bar(orders, ang)
plt.show()
```

#430 method to extract harmonic data from transient results

---

src/ansys/motorcad/core/methods/rpc_methods_graphs.py

Implements a trivial DFT for the harmonic graph calculation. For normal Motor-CAD graph lengths, the speed penalty compared to an FFT should not be significant.

Remove numpy dependency for harmonic graph calculation

---

src/ansys/motorcad/core/methods/rpc_methods_variables.py
tests/test_variables.py

Fixes #461 
This checks the Motor-CAD version in get_file_name, as the underlying API call was only added to Motor-CAD 2025 R1. 
If the Motor-CAD version does not implement the API call, this falls back to returning the variable CurrentMotFilePath_MotorLAB which should match the Motor-CAD file name. This isn't necessary, but may be helpful for users running a newer PyMotorCAD than Motor-CAD.

Add version checking and backwards compatibility for file name check

---

src/ansys/motorcad/core/rpc_client_core.py

Fixes cwd of Motor-CAD being wrong when launching from automation. 
To replicate bug
1. Create a file with an external lab model file with a relative path:
2. Launch Motor-CAD using PyMotorCAD and load the file.
3. Reload model import - previously file cannot be found

Fix CWD when launching Motor-CAD

---

src/ansys/motorcad/core/geometry.py

Overkill and regression tests break if dxf regions change order in tree

Remove colour check in region equality.

---

src/ansys/motorcad/core/geometry.py
tests/test_geometry.py

get_region() calls Region._from_json. Following #477 this was generating a warning, because we were setting the region type after the region was created. This PR avoids this warning being raised.

Avoid warning about setting region type when creating with get_region

---

src/ansys/motorcad/core/rpc_client_core.py

Needed for https://github.com/ansys-internal/motor-cad/pull/2290
Needs review by @matthewAnsys 
This might also be useful for running tests on different version of Motor-CAD.
Not bothered about code coverage for this as it will be extensively used by Motor-CAD regression testing

Add ability to set default Motor-CAD exe from environment variable

---

examples/adaptive_library/RoundParallelSlotBttm.py
src/ansys/motorcad/core/geometry.py

Updated several enum types in the RegionType Class, which previously did not match with their corresponding strings in Motor-CAD and resulted in errors when users attempted to get said regions.

Fixed incorrect RegionType enums

---

src/ansys/motorcad/core/methods/rpc_methods_fea_geometry.py

The save_fea_data documentation wasn't very informative, so I have updated this to include a description of the parameters. Additionally, the depreciation warnings for some functions were incorrectly appearing as part of the parameter list, so these have been moved to render correctly.

Add more information to save_fea_data documentation, and move deprecation warnings so they render correctly.

---

src/ansys/motorcad/core/geometry.py
tests/test_geometry.py

For regions with high curvature, the standard FEA mesh density approach does not take into account that higher mesh density is required to capture the curvature. This allows users to split the arcs in a region, to force a finer FEA mesh (as we will always have at least one mesh element per arc).

Allow FEA mesh control around high curvature regions by dividing arcs

---

tests/test_rpc_client_core.py

Causing issues with Motor-CAD regression testing

Disable blackbox test if using web licensing

---

examples/advanced/stress_postprocessing.py

Depending on Motor-CAD versions, the region name may be the 7th or 8th item in the RegionsTable list, but always at the end. Pick the end element to make this more robust.

Make this more robust for different Motor-CAD versions

---

src/ansys/motorcad/core/geometry.py
tests/test_geometry.py

EntityList equality evaluation was previously evaluating whether the first list was a subset of the second. The new behaviour is as expected.

Fix Incorrect EntityList equality evaluation

---

README.rst
doc/source/contributing.rst

The old instructions to use `python -m pip install --editable ansys-motorcad-core` don't work, as the --editable option requires a path, instead of a package name. As long as we are in the correct directory, this path can just be `.`.

Update pip install instructions for editable mode.

---

.github/workflows/ci_cd.yml
.github/workflows/nightly-motorcad-check.yml
.pre-commit-config.yaml
doc/source/getting_started/index.rst
pyproject.toml
tox.ini

More recent versions of Sphinx require Python 3.11 to run, so this changes the CI from running in 3.10 to 3.12.

Update ci_cd.yml to run on Python 3.12

---

tests/test_general.py

Motor-CAD test runner has duplicate materials saved to database. This means there are more than 30 lines changed between the base and uploaded file.

Add more tolerance to tests.

---

src/ansys/motorcad/core/geometry.py

By default new Regions are created with colour = (0, 0, 0)
This displays as black, and with new draw_objects updates, it makes seeing labels/points difficult, as well as overlapping regions: 
Propose changing this to white = (255, 255, 255) for easier visibility.

Change the default colour attribute of new Region objects
