.github/workflows/ci_cd.yml, src/ansys/motorcad/core/__init__.py
change the main version after the release.
=> MAINT : Bump 0.2.dev version

doc/source/conf.py
=> DOC : fix version on the docs

.github/workflows/ci_cd.yml, doc/source/conf.py
=> doc: fix the bug to deploy dev docs.

.github/workflows/ci_cd.yml, .github/workflows/label.yml, README.rst, doc/source/conf.py, doc/source/contributing.rst, doc/source/getting_started/index.rst, doc/source/index.rst, pyproject.toml
Update the repository re-Org rename.
=> MAINT: Update the name of the org.

.github/workflows/ci_cd.yml, pyproject.toml, src/ansys/motorcad/core/__init__.py
=> fix: update ci_cd

tests/test_calculations.py, tests/test_fea_geometry.py, tests/test_general.py, tests/test_lab.py
(cherry picked from commit 5c2b7db3e3db650d78afe69e24cb8a8c010e7228)
=> 0.2 - Update tests for latest motorcad version (#183)

examples/basics/emag_basics.py, examples/basics/lab_basics.py
Address Issue #212. In the example notebooks the markdown was not rendering correctly. I also eliminated references to ActiveX.
=> Fix minor rendering errors.

tests/test_fea_geometry.py, tests/test_geometry.py, tests/test_graphs.py
(cherry picked from commit b1eb3ddde5d71b6ebd9fb38ca0d446327a72e3c7)
=> Update tests for 24r1

src/ansys/motorcad/core/methods/rpc_methods_calculations.py, tests/test_calculations.py
Windings not updated when winding input parameters changed. Add a method to update winding pattern without performing calculation
=> Create windings method

src/ansys/motorcad/core/methods/rpc_methods_general.py
To make the functionality clearer (in line with menu in GUI)
Previously, it wasn't clear what the different options were for. Now the same info from the menu in GUI is given in the Docstring
=> Updated Documentation for export_results()

src/ansys/motorcad/core/geometry.py, tests/test_geometry.py
Closes #329 
See unit tests for examples
=> Missing tolerance Arc.centre property

examples/links/ece_export_for_twinbuilder.py
Updated the TB ECE model example to distinguish between it and the Thermal example.
New naming mirrors existing Thermal example. New naming approved by J.God
=> updated ECE export example name

src/ansys/motorcad/core/geometry_drawing.py, tests/test_geometry_drawing.py
Issue caused by algorithm trying the same point repeatedly 
@JackB-Ansys Can you test this with your file?
=> Fix max recursion depth reached with geometry drawing

tests/test_graphs.py
Update values used in tests, and relax test tolerance for graphs tests.
=> Fix graph tests following change to motor test file in #411.

examples/adaptive_library/TrapezoidalDuct.py
Simplify point calculation using get_coordinate_from_distance() method. Fixes issues with half ducts.
=> Fix for Trapezoid Duct Adaptive Templates Example

doc/source/_static/custom.css, doc/source/conf.py
Idea coming from https://github.com/sphinx-gallery/sphinx-gallery/issues/1205
=> docs: remove download jupyter nb

doc/source/methods/geometry_fitting.rst, doc/source/methods/geometry_functions.rst, doc/source/methods/index.rst, src/ansys/motorcad/core/geometry.py, src/ansys/motorcad/core/methods/rpc_methods_graphs.py, src/ansys/motorcad/core/methods/rpc_methods_variables.py, src/ansys/motorcad/core/motorcad_methods.py, src/ansys/motorcad/core/rpc_client_core.py, tests/test_geometry.py, tests/test_graphs.py, tests/test_rpc_client_core.py, tests/test_variables.py
Cherry pick:
#458, #445
#462 
#466 
#472 
#446
=> Cherrypick 0.7.2

examples/adaptive_library/BPMTriangularRotorNotches.py, examples/adaptive_library/BezierCurveRotorPockets.py, examples/adaptive_library/DXFImport.py, examples/adaptive_library/OblongStatorDuct.py, examples/adaptive_library/RoundParallelSlotBttm.py, examples/adaptive_library/TrapezoidalDuct.py, examples/adaptive_library/UShapeSYNCRELCurvedFluxBarriers.py, examples/adaptive_library/UpdateMaterialMesh.py, examples/basics/emag_basics.py, tests/conftest.py, tests/test_UI.py, tests/test_rpc_client_core.py
Change Motor-CAD tests to use no UI. Should speed things up considerably
=> Update tests to use Motor-CAD with no UI

samples/general/MotionForceExport.py
This provides an example of exporting force data in the format required to load into an Ansys Motion multibody model, with additional parameters to control the angular offset.
=> Motion force export

src/ansys/motorcad/core/methods/adaptive_geometry.py, tests/test_geometry.py
Updated the default to improve backwards compatibility.
=> Update default in get_region() so defaults to get_linked=False.
